title: basic-512-bs=40
log_dir: ../log/
mode: train_dev
use_wandb: False
seeds: [1, 2, 3]
data:
  path: ../data/origin
  num_workers: 12
  num_classes: 4
  seq_len: 512
  augmentation: False
model:
  encoder: ../models/Lawformer
  dropout: 0.1
  device: "cuda:2"
  device_ids: [2, 3]
  loss_fn: MSELoss
  pooler: mean
  head: cosine
optimizer:
  name: Adam
  lr: 0.00001
  scheduler: cos
train:
  batch_size: 40
  eval_batch_size: 100
  num_epochs: 5
