title: basic-512-concat
log_dir: ../log/
mode: train_dev
use_wandb: False
seeds: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
data:
  path: ../data/origin
  num_workers: 12
  num_classes: 4
  seq_len: 512
  crop_candidate: True
model:
  encoder: ../models/Lawformer
  dropout: 0.1
  device: "cuda:0"
  loss_fn: BCELoss
  head: concat
optimizer:
  name: Adam
  lr: 0.00002
  scheduler: cos
train:
  batch_size: 22
  eval_batch_size: 256
  num_epochs: 20
