title: bm25-512
log_dir: ../log/
mode: train_dev
use_wandb: False
seeds: [1, 2, 3]
data:
  path: ../data/bm25
  num_workers: 12
  num_classes: 4
  seq_len: 512
  query_seq_len: 256
  candidate_seq_len: 512
  augmentation: False
model:
  type: cross
  encoder: ../models/Lawformer
  dropout: 0.1
  device: "cuda:2"
  device_ids: [2, 3]
  loss_fn: BCEWithLogitsLoss
  pooler: cls
  head: regression
optimizer:
  name: Adam
  lr: 0.00001
  scheduler: cos
train:
  batch_size: 40
  eval_batch_size: 100
  num_epochs: 20
