title: bm25-512-train
log_dir: ../log/
mode: train
use_wandb: False
seeds: [1,2,3,4,5,6,7,8,9,10]
data:
  path: ../data/bm25
  num_workers: 12
  num_classes: 4
  seq_len: 512
  augmentation: False
model:
  encoder: ../models/Lawformer
  dropout: 0.1
  device: "cuda:3"
  loss_fn: MSELoss
  head: cosine
optimizer:
  name: Adam
  lr: 0.00001
  scheduler: cos
train:
  batch_size: 22
  eval_batch_size: 100
  num_epochs: 2
