title: reranker-512-512-bi
log_dir: ../log/
mode: train_dev
use_wandb: False
seeds: [1, 2, 3]
data:
  path: ../data/origin
  num_workers: 12
  num_classes: 3
  query_seq_len: 512
  candidate_seq_len: 512
  augmentation: False
  label_type: rerank
model:
  type: bi
  encoder: ../models/Lawformer
  dropout: 0.1
  device: "cuda:3"
  device_ids: [3]
  loss_fn: MSELoss
  pooler: mean
  head: cosine
optimizer:
  accumulation_steps: 1
  name: Adam
  lr: 0.00002
  scheduler: cos
train:
  batch_size: 22
  eval_batch_size: 200
  num_epochs: 5
