title: retriever3-512-512-bi
log_dir: ../log/
mode: train_dev
eval_only: True
use_wandb: False
seeds: [1]
data:
  path: ../data/origin
  num_workers: 12
  num_classes: 2
  query_seq_len: 512
  candidate_seq_len: 512
  augmentation: False
  label_type: retrieve3
model:
  type: bi
  encoder: ../models/Lawformer
  dropout: 0.1
  device: "cuda:0"
  device_ids: [0]
  loss_fn: MSELoss
  pooler: mean
  head: cosine
optimizer:
  accumulation_steps: 1
  name: Adam
  lr: 0.00002
  scheduler: cos
train:
  batch_size: 22
  eval_batch_size: 20
  num_epochs: 2
